// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnr2tOIgS6lEfj176403pK3TZiX4F6lE',
    appId: '1:620640570643:web:02cf70eed9094e4c229ee6',
    messagingSenderId: '620640570643',
    projectId: 'messageapp-5bc4d',
    authDomain: 'messageapp-5bc4d.firebaseapp.com',
    storageBucket: 'messageapp-5bc4d.firebasestorage.app',
    measurementId: 'G-KDS5RZCPYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg37BehqEtqLWEa2hOWJYv2uQ1ZTdYtCY',
    appId: '1:620640570643:android:7075cd6cd4a38c33229ee6',
    messagingSenderId: '620640570643',
    projectId: 'messageapp-5bc4d',
    storageBucket: 'messageapp-5bc4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkp0IOtz5JVlbcjzRrTxfrn6nN4ANLAHc',
    appId: '1:620640570643:ios:4cd949c55078e271229ee6',
    messagingSenderId: '620640570643',
    projectId: 'messageapp-5bc4d',
    storageBucket: 'messageapp-5bc4d.firebasestorage.app',
    androidClientId: '620640570643-9rrdmokbahl263ccmmifkkv38h8geqp8.apps.googleusercontent.com',
    iosClientId: '620640570643-3nk5bdp50m9crgalstgvt2jlj40b9u9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkp0IOtz5JVlbcjzRrTxfrn6nN4ANLAHc',
    appId: '1:620640570643:ios:4cd949c55078e271229ee6',
    messagingSenderId: '620640570643',
    projectId: 'messageapp-5bc4d',
    storageBucket: 'messageapp-5bc4d.firebasestorage.app',
    androidClientId: '620640570643-9rrdmokbahl263ccmmifkkv38h8geqp8.apps.googleusercontent.com',
    iosClientId: '620640570643-3nk5bdp50m9crgalstgvt2jlj40b9u9o.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnr2tOIgS6lEfj176403pK3TZiX4F6lE',
    appId: '1:620640570643:web:abfc1bbdc50c18b0229ee6',
    messagingSenderId: '620640570643',
    projectId: 'messageapp-5bc4d',
    authDomain: 'messageapp-5bc4d.firebaseapp.com',
    storageBucket: 'messageapp-5bc4d.firebasestorage.app',
    measurementId: 'G-CDG2LTRMFV',
  );
}
